# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: G:/verilog/EXP-10/exp-10/exp-10.srcs/sources_1/ip/shift_ram/shift_ram.xci
# IP: The module: 'shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/verilog/EXP-10/exp-10/exp-10.srcs/sources_1/ip/shift_ram/shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: G:/verilog/EXP-10/exp-10/exp-10.srcs/sources_1/ip/shift_ram/shift_ram.xci
# IP: The module: 'shift_ram' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/verilog/EXP-10/exp-10/exp-10.srcs/sources_1/ip/shift_ram/shift_ram_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'shift_ram'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
